# dev (Development)
# A profile for the development environment. The database is using external.
# The default setting is to prevent the database from being recreated during execution.

server:
  port: 5678

spring:
  datasource:
    url: ${EXTERNAL_DB_URL} # '${{ secrets.EXTERNAL_DB_URL }}' 이라고 해도 됨.
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${EXTERNAL_DB_USERNAME}
    password: ${EXTERNAL_DB_PASSWORD}

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  application:
    name: DonGiveUpBE