# local
# A profile for the local development environment.
# Includes settings that the developer personally uses.

server:
  port: 5678

spring:
  datasource:
    url: ${LOCALHOST_DB_URL}
    driver-class-name:
    username: ${LOCALHOST_DB_USERNAME}
    password: ${LOCALHOST_DB_PASSWORD}

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  application:
    name: DonGiveUpBE