server:
  port: 5678

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  application:
    name: DonGiveUpBE