# prod (Production)
# 실제 운영 환경을 위한 프로파일. (A profile for the actual production environment.)
# 보안, 성능 최적화, 데이터베이스 연결 등의 설정을 포함함. (Includes settings for security, performance optimization, and database connections.)

server:
  port: 5678

spring:
  datasource:
    url: ${AWS_DB_URL}
    driver-class-name:
    username: ${AWS_DB_USERNAME}
    password: ${AWS_DB_PASSWORD}

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  application:
    name: DonGiveUpBE