# local
# 로컬 개발 환경을 위한 프로파일
# 개발자가 개인적으로 사용하는 설정을 포함.

server:
  port: 5678

spring:
  datasource:
    url: ${EXTERNAL_DB_URL}
    driver-class-name:
    username: ${EXTERNAL_DB_USERNAME}
    password: ${EXTERNAL_DB_PASSWORD}

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  application:
    name: DonGiveUpBE