spring:
  profiles:
    active: prodCreate # when deploy -> prod
    # local (ddl-auto: none, DataLoader X, LocalDB)
    # localCreate (ddl-auto: create, DataLoader O, LocalDB)
    # prod (ddl-auto: none, DataLoader X, AWS DB)
    # prodCreate (ddl-auto: create, DataLoader O, AWS DB)