spring:
  profiles:
    active: prod # when deploy -> prod
    # local (ddl-auto: none, DataLoader X, LocalDB)
    # localCreate (ddl-auto: create, DataLoader O, LocalDB)
    # prod (ddl-auto: create, DataLoader O, AWS DB)